export  const fullLyric = [
  {lyric: "My baby I love you so much forever you and I", time: 5},
  {lyric: "I love you oh~I love you so much forever you and I", time: 6},
  // {lyric: "My baby I love you so much forever you and I", time: 5},
  // {lyric: "I love you oh I love you so much forever you and I", time: 6},
  // {lyric: "Vẫn nhớ ánh mắt, nhớ đôi ngày nào bên anh", time: 2},
  // {lyric: "Và nụ cười tươi xinh của người", time: 2},
  // {lyric: "Vẫn nhớ những lúc bên em mình kề vai nhau", time: 2},
  // {lyric: "Oh cuộc đời ôi sao tuyệt với oh", time: 2},
  // {lyric: "Trong tim anh chỉ yêu riêng 1 mình em", time: 2},
  // {lyric: "Mà người nào đâu hay biết tới", time: 2},
  // {lyric: "Và có những lúc trong mơ gọi thầm tên em", time: 2},
  // {lyric: "Vì giờ người xa anh thật rồi", time: 2},
  // {lyric: "Please tell me why Sao em ra đi không một lời nói", time: 2},
  // {lyric: "Please tell me why Con tim anh không sao quên được người", time: 2},
  // {lyric: "Please tell me why Cho anh hay sao em lại đành nói", time: 2},
  // {lyric: "Lời chia tay khi biết anh vẫn luôn luôn thật lòng yêu em", time: 2},
  // {lyric: "Và thâm chờ mong em trở về", time: 2},
  // {lyric: "My baby I love you so much forever you and I", time: 2},
  // {lyric: "I love you oh~I love you so much forever you and I", time: 2},
  // {lyric: "My baby I love you so much forever you and I", time: 2},
  // {lyric: "I love you oh I love you so much forever you and I", time: 2},
  // {lyric: "Những lúc xa anh trong lòng nhung nhớ", time: 2},
  // {lyric: "Dẫu biết anh yêu không về với em", time: 2},
  // {lyric: "Nhưng em vẫn luôn luôn tin rằng", time: 2},
  // {lyric: "Ngày nào đó anh yêu quay về", time: 2},
  // {lyric: "Sẽ mãi bên nhau không rời anh nữa", time: 2},
];

export const SECOND = 1000; 
